config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  root to: 'users#index'
  get 'signup', to: 'users#new'
  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/club', to: 'pages_club#club'

  get '*path' => redirect { |p, req| req.flash[:error] = "Pour acceder à cette page log toi 😉"; '/login' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_secure_password
  validates :password, presence: true, length:{minimum: 6}
  validates :first_name, presence: true, length:{minimum: 3}
  validates :last_name, presence: true, length:{minimum: 3}
  validates :first_name, presence: true, length:{minimum: 3}
  validates :email, presence: true, uniqueness: true

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  def forget
    update_attribute(:remember_digest,nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/pages_club_controller.rb
class PagesClubController < ApplicationController

   before_action :logged_in_user, only: [:club]

   def club
     @users = User.all
   end


  # Confirms a logged-in user.
 def logged_in_user
   unless logged_in?

     flash[:danger] = "Please log in."
     redirect_to login_url
   end
 end

 # Confirms the correct user.

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_to user
    else
      flash.now[:danger] = 'Mot de passe ou email incorrect'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.all
  end

  def club
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_club_helper.rb
module PagesClubHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    #envoie un cookie temporaire
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Club privée", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Home", root_path %></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Club", club_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClubPrivee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>

    <h3><% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %></h3>
      <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/pages_club/club.html.erb
<h1>les Clubbers</h1>
<div class="container">
<h3> Listing </h3>
<br>
<br>
<table>
  <thead>
    <tr>
      <th>Prénom</th>
      <th>Nom</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
  <h1>Sign up</h1>

  <div class="row w-50 p-3">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
      <%= render 'shared/error_message' %>
        <div class="form-group">
        <%= f.label :Prénom %>
        <%= f.text_field :first_name,class: "form-control" %>
        <div class="form-group">
        <%= f.label :Nom %>
        <%= f.text_field :last_name,class: "form-control" %>
        <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email,class: "form-control" %>
        </div>
        <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password,class: "form-control" %>
        </div>
        <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation,class: "form-control" %>
        </div>

        <%= f.submit "Let's go", class: "btn btn-info" %>
      <% end %>
    </div>
  </div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Club privée du soleil</h1>

<h2>Tu cherches des Clubs privées ?</h2>

<h3><%= link_to 'Une Inscription suffira', signup_path %></h3>

<h5>
<a href="signup"><img src="http://www.acoustix.be/wp-content/uploads/2017/10/Isolation-acoustique-discotheque-sous-sol-hotel-Acoustix-Pan-terre-3.jpg" alt=""></a>
</h5>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Bonjour <%= @user.first_name %></h1>


<h2><%= link_to 'la fameuse liste', club_path %></h2>


<h5>
  <strong>First name:</strong>
  <%= @user.first_name %>
</h5>

<h5>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</h5>

<h5>
  <strong>Email:</strong>
  <%= @user.email %>
</h5>

<h5>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>|
<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>